### ISSUE TITLE
API v1 Roadmap

### ISSUE THREAD

**Issue by Aeltumn** [Aeltumn/autumn_kingdoms_api#1]
The following functionality still needs to be added to the API:
- [x] Allow expansion packs to be defined without the API knowing of their existance (API will still have a master list of expansions it expects to find but should accept others)
- [x] Settings system that allows you to add new settings to the /kd settings menu
- [x] Ability to add a new view or skin to the /kd panel menu
- [x] `Title` interface to get the title of a player if they have one, the title can be used to determine what kind of internal permissions (not bukkit permissions) this title has. These internal permissions include things like "Can invite new members", "Can access menu X in the panel", etc. Titles are also a `Group`
- [x] `Kingdom` interface and new methods in KingdomAPI to get the kingdom of any player, including `Group` interface which will denote a generic bundle of players that can have certain things they are allowed to do
- [x] Abstract `Region` system where you can fetch what kind of region a block belongs to, these regions will basically be the same as asking 'which kingdoms can build here?' but with the option to specify what kind of interaction should(n't) be allowed for which `Group`
- [x] ~~Chat system where you can overwrite the custom chat format or add/remove chat channels~~

**Comment by Aeltumn** [comment]
All planned APIs except for the chat system have been (partially) implemented on the develop branch. Chat system is dropped as it's not essential.
